header<- read.table("household_power_consumption.txt",sep=";",nrows=1,header=TRUE,colClasses = c("Date","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"),stringsAsFactors=FALSE)
x<-read.table("household_power_consumption.txt",sep=";",skip=66637,nrows=2880)
names(x)<-names(header)
x$DateTime<-strptime(paste(x$Date,x$Time,sep=" "),"%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2),mar=c(4,4,2,2))
plot(x$DateTime,x$Global_active_power,type="l",ylab="Global Active Power",xlab="")
plot(x$DateTime,x$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(x$DateTime,x$Sub_metering_1,type="n",,xlab="",ylab="Energy sub metering")
lines(x$DateTime,x$Sub_metering_1,type="l")
lines(x$DateTime,x$Sub_metering_2,type="l",col="red")
lines(x$DateTime,x$Sub_metering_3,type="l",col="blue")
legend("topright",lwd=1,col=c("black","red","blue"),legend = c("sub_metering1","sub_metering2","sub_metering3"),bty="n")
plot(x$DateTime,x$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()